name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile war:war --file pom.xml
    - name: Rename file 
      run: mv /home/runner/work/RechnunglessConverter/RechnunglessConverter/target/*.war ./rechnungless.war
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./rechnungless.war"
#    - name: Rename file 
#      run: cp /home/runner/work/RechnunglessConverterTEST/RechnunglessConverterTEST/target/rechnungless.war ./rechnungless.war
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Build Image'
      run: |
        docker build . --tag ghcr.io/${{github.repository_owner}}/rechnunglessconverter:${{github.ref_name}} --tag ghcr.io/${{github.repository_owner}}/rechnunglessconverter:latest
        docker push ghcr.io/${{github.repository_owner}}/rechnunglessconverter --all-tags
